apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: logging-cluster
  region: ap-northeast-2 
  version: "1.29"

iam:
  withOIDC: true

vpc:
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-002b82be982d1da9d
      ap-northeast-2b:
        id: subnet-01b07e9aa7448f3b3

managedNodeGroups:
  - name: app-nodegroup
    minSize: 2
    desiredCapacity: 2
    maxSize: 16
    labels:
      node: app
    instanceType: c5.large
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true

