apiVersion: v1
data:
  cluster.name: "wsi-eks-cluster"
  logs.region: "ap-northeast-2"
  http.server: "On"
  http.port: "2020"
  read.head: "Off"
  read.tail: "On"
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info 
  namespace: app

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: app

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-role
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/logs
      - nodes
      - nodes/proxy
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-role
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: app

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: app
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                     5
        Grace                     30
        Log_Level                 info
        Daemon                    off
        HTTP_Server               ${HTTP_SERVER}
        HTTP_Listen               0.0.0.0
        HTTP_Port                 ${HTTP_PORT}
        storage.path              /var/fluent-bit/state/flb-storage/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 5M

    @INCLUDE application-log.conf

  application-log.conf: |
    [INPUT]
        Name                tail
        Tag                 app1
        Path                /app1/*.log

    [INPUT]
        Name                tail
        Tag                 app2
        Path                /app2/*.log

    [INPUT]
        Name                tail
        Tag                 app3
        Path                /app3/*.log

    [OUTPUT]
        Name          forward
        Match         app1
        Host          fluentd.fluentd.svc.cluster.local
        Port          24224
        tls           off
        tls.verify    off
    
    [OUTPUT]
        Name          forward
        Match         app2
        Host          fluentd.fluentd.svc.cluster.local
        Port          24224
        tls           off
        tls.verify    off

    [OUTPUT]
        Name          forward
        Match         app3
        Host          fluentd.fluentd.svc.cluster.local
        Port          24224
        tls           off
        tls.verify    off